### PR TITLE
Db active

### PR DESCRIPTION
**Pull request by Adobe-Android**
Created error handling for a user passing in an id that doesn't correspond with a valid id in the database. Please test: Select option 2 and then input an invalid active user id number. You should then see the error  being handled and the menu restarting.

### CODE REVIEW

**Comment by glenvollmer** [comment]
typed in "f" and it accepted it as a customer id. you may need to refactor how it handles characters that are not numbers...

**Comment by DLWalker1234** [comment]
I agree with Glen

**Comment by Staffmaster00** [comment]
I agree with the agreeing of Glen

**Comment by Adobe-Android** [comment]
We fixed it accepting strings and we removed the + symbol which checks for one or more matches. This previously caused answers like 12 which contain both 1 and 2 to work. References: http://www.pnotepad.org/docs/search/regular_expressions/
https://stackoverflow.com/questions/17885855/use-dynamic-variable-string-as-regex-pattern-in-javascript

**Comment by glenvollmer** [comment]
dude we killed it! lets merge it in and handle other inputs in a similar fashion

**Pull request merged**
